// The Finally Clause :
const f = () => {
    try {
        let a = 0;
        console.log(program)
        console.log("Program can run successfully")
        // return

    } catch (err) {
        console.log("This is an Error")
        console.log(p);
    }
    finally {
        console.log("I am Good Boy");
        // Close the File.
        // Exist the Loop.
        // Write to the Log File.
    }
}
f();
console.log("End");